# Generated by Django 4.0.3 on 2023-03-25 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='exp_date',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
